'use strict';
/* أكاديمية الإمام v10 — data-model + session workflow extension */
const V10={reviewResults:{},accordion:{errors:false,suggestion:false},library:{hadithFilter:'الكل',duaFilter:'الكل'},mushafDownload:null};
const V10_JUZ_RANGES=[[1,2],[2,2],[2,2],[2,4],[4,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,11],[11,12],[12,14],[15,16],[17,18],[18,20],[20,21],[21,23],[23,25],[25,27],[27,29],[29,33],[33,36],[36,39],[39,41],[41,45],[46,51],[51,57],[58,66],[67,77],[78,114]];
const V10_THEMES={
 A:{name:'Emerald & Ivory',p:'#145A3A',d:'#0C3B28',a:'#C9A84C',bg:'#F7F4EC'},
 B:{name:'Deep Teal & Sand',p:'#0D5B55',d:'#083E3A',a:'#C6A15B',bg:'#F7F2E8'},
 C:{name:'Forest & Warm White',p:'#214E3A',d:'#153428',a:'#D0AE61',bg:'#FAF8F3'},
 D:{name:'Navy Islamic',p:'#173D4E',d:'#102B37',a:'#CBA85C',bg:'#F5F7F5'}
};
// Only source-backed starter records are bundled. The library UI explicitly refuses unsourced/generated content.
const V10_HADITH=[
 {id:'bukhari-10',text:'الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ',narrator:'عبد الله بن عمرو رضي الله عنهما',source:'صحيح البخاري',hadithNumber:'10',grade:'صحيح',category:'الأخلاق',reference:'Sahih al-Bukhari 10'},
 {id:'bukhari-1',text:'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ',narrator:'عمر بن الخطاب رضي الله عنه',source:'صحيح البخاري',hadithNumber:'1',grade:'صحيح',category:'النية',reference:'Sahih al-Bukhari 1'},
 {id:'bukhari-13',text:'لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',narrator:'أنس بن مالك رضي الله عنه',source:'صحيح البخاري',hadithNumber:'13',grade:'صحيح',category:'الأخلاق',reference:'Sahih al-Bukhari 13'},
 {id:'bukhari-6018',text:'مَنْ لاَ يَرْحَمْ لاَ يُرْحَمْ',narrator:'جرير بن عبد الله رضي الله عنه',source:'صحيح البخاري',hadithNumber:'6013/6018 بحسب الترقيم',grade:'صحيح',category:'الرحمة',reference:'صحيح البخاري — كتاب الأدب؛ يراجع الترقيم بحسب الطبعة'}
];
const V10_DUA=[
 {id:'hisn-sleep-1',text:'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',occasion:'قبل النوم',source:'صحيح البخاري',repeatCount:1,category:'قبل النوم',reference:'صحيح البخاري 6324'},
 {id:'hisn-wake-1',text:'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',occasion:'الاستيقاظ',source:'صحيح البخاري',repeatCount:1,category:'الاستيقاظ',reference:'صحيح البخاري 6312'},
 {id:'hisn-toilet-out',text:'غُفْرَانَكَ',occasion:'الخروج من الخلاء',source:'سنن أبي داود',repeatCount:1,category:'الخروج',reference:'سنن أبي داود 30'},
 {id:'hisn-home-out',text:'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ',occasion:'الخروج من المنزل',source:'سنن أبي داود',repeatCount:1,category:'الخروج',reference:'سنن أبي داود 5095'}
];
function v10Id(p='x'){return globalThis.makeId?makeId(p):`${p}-${Date.now()}-${Math.random().toString(36).slice(2)}`}
function v10Esc(x){return globalThis.esc?esc(x):String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function v10NormalizeGrade(g){return g==='جيد جدًا'?'جيد جداً':g;}
function v10SurahItem(name,status='not_heard'){const n=String(name||'').replace(/^سورة\s+/,'').trim(),idx=S.findIndex(s=>s.n===n);if(idx<0)return null;return{id:`surah-${idx+1}`,type:'surah',surahId:idx+1,surahName:S[idx].n,status,evaluation:'',errors:[],notes:''};}
function v10ExpandJuz(name){const idx=JZ.indexOf(name);if(idx<0)return[];const range=V10_JUZ_RANGES[idx]||[];return S.slice(range[0]-1,range[1]).map(s=>v10SurahItem(s.n)).filter(Boolean);}
function v10Assignment(type,name,chips=[]){let items=[];for(const chip0 of chips){const chip=String(chip0||'').trim();if(chip.startsWith('جزء '))items.push(...v10ExpandJuz(chip));else{const it=v10SurahItem(chip);if(it)items.push(it);}}const seen=new Set();items=items.filter(i=>!seen.has(i.id)&&seen.add(i.id));return{id:v10Id('rev'),type,groupId:type==='juz'?name.replace(/\s+/g,'-'):v10Id('group'),groupName:name,items};}
function v10Migrate(){let changed=false;settings.v10=settings.v10||{};settings.facebookUrl=settings.facebookUrl||'https://www.facebook.com/AlImamEdu';settings.themePalette=settings.themePalette||'A';settings.contentAssignments=settings.contentAssignments||{};for(const ses of sessions){if(!Array.isArray(ses.reviewAssignments)){const arr=[];if(ses.juz?.chips?.length)arr.push(v10Assignment('juz','مراجعة الأجزاء',ses.juz.chips));if(ses.surahReview?.chips?.length)arr.push(v10Assignment('surah_group','مراجعة السور',ses.surahReview.chips));ses.reviewAssignments=arr;changed=true;}if(!ses.reviewResults)ses.reviewResults={};}
 if(changed)save();applyV10Theme(settings.themePalette);}
function applyV10Theme(key='A'){const t=V10_THEMES[key]||V10_THEMES.A;document.documentElement.style.setProperty('--gm',t.p);document.documentElement.style.setProperty('--gd',t.d);document.documentElement.style.setProperty('--gold',t.a);document.documentElement.style.setProperty('--bg',t.bg);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',t.p);settings.themePalette=key;}
function setV10Theme(key){applyV10Theme(key);save();renderV10ThemeSettings();}
function v10Accordion(id,title,body,open=false,extra=''){return `<section class="v10-accordion ${open?'open':''}" id="${id}"><button type="button" aria-expanded="${open}" onclick="toggleV10Accordion('${id}')"><span>${title}</span><span class="v10-chevron">⌄</span></button><div class="v10-accordion-body">${extra}${body}</div></section>`;}
function toggleV10Accordion(id){const el=document.getElementById(id);if(!el)return;const open=!el.classList.contains('open');el.classList.toggle('open',open);el.querySelector(':scope > button')?.setAttribute('aria-expanded',String(open));V10.accordion[id==='v10ErrorsAccordion'?'errors':'suggestion']=open;scheduleDraftSave?.();}
function enhanceSessionAccordions(){const card=document.getElementById('sessionErrorsCard');if(card&&!card.dataset.v10){card.dataset.v10='1';card.classList.add('v10-accordion');card.id='v10ErrorsAccordion';const children=[...card.children];card.innerHTML=`<button type="button" aria-expanded="false" onclick="toggleV10Accordion('v10ErrorsAccordion')"><span>سجل أخطاء التسميع <small class="txt-mut" id="errorCountLabel">0 خطأ</small></span><span class="v10-chevron">⌄</span></button><div class="v10-accordion-body"></div>`;const body=card.querySelector('.v10-accordion-body');children.forEach(c=>{if(c.querySelector?.('#errorCountLabel'))c.remove();else body.appendChild(c);});}
 const target=document.querySelector('#prevCard');if(target&&!document.getElementById('v10SuggestionAccordion'))target.insertAdjacentHTML('afterend',v10Accordion('v10SuggestionAccordion','اقتراح المراجعة','<div id="v10SuggestionBody" class="v10-empty">سيظهر هنا تلقائيًا ما يحتاج إعادة أو لم يُسمع، مع بقاء القرار النهائي للمحفظ.</div>',false));}
function v10Prev(){const dateKey=document.getElementById('sesDate')?.value||localDateKey();return curStId?getPreviousPresentSession(curStId,dateKey,editingSessionId||''):null;}
function openQuranRangeText(sec){if(!sec?.surah)return toast('لا يوجد نطاق نص متاح','error');const idx=S.findIndex(s=>s.n===sec.surah);if(idx<0)return;V8.quranRange={chapter:idx+1,surah:sec.surah,from:Number(sec.from)||1,to:Number(sec.to)||S[idx].a,max:S[idx].a};document.getElementById('quranModalTitle').textContent=`📖 سورة ${sec.surah} — الآيات ${V8.quranRange.from} إلى ${V8.quranRange.to}`;document.getElementById('quranTextModal').classList.add('open');const content=document.getElementById('quranVerseContent');content.innerHTML='<div class="quran-load">جارٍ تحميل النص العثماني…</div>';fetchQpcHafsChapter(idx+1).then(all=>{V8.quranVerses=all.filter(v=>v.ayah>=V8.quranRange.from&&v.ayah<=V8.quranRange.to);content.innerHTML=V8.quranVerses.map(v=>`<span class="quran-ayah" data-ayah="${v.ayah}">${v10Esc(v.text)} <span class="quran-ayah-num">${v.ayah}</span></span>`).join(' ');setQuranPane?.('text');}).catch(()=>content.innerHTML='<div class="empty"><p>تعذر تحميل النص الآن، وإن كان محفوظًا Offline فسيُستخدم تلقائيًا عند توفره.</p></div>');}
function openPrevQuranText(key){const p=v10Prev();if(p?.[key])openQuranRangeText(p[key]);}
function repeatPrevAssignment(key){const p=v10Prev(),x=p?.[key];if(!x)return;if(['new','rec','far'].includes(key)){secOn[key]=true;updateTogs();document.getElementById(key+'-s').value=x.surah;fillAyah(key);document.getElementById(key+'-full').checked=!!x.full;toggleFull(key);if(!x.full){document.getElementById(key+'-f').value=x.from;document.getElementById(key+'-t').value=x.to;}document.getElementById(key+'-s').dataset.userTouched='1';}scheduleDraftSave();toast('تمت إضافة نفس التكليف للحصة القادمة — يمكنك تعديله قبل الحفظ','success');}
function setReviewItemStatus(groupId,itemId,status){V10.reviewResults[groupId]=V10.reviewResults[groupId]||{};V10.reviewResults[groupId][itemId]={status,updatedAt:new Date().toISOString()};document.querySelectorAll(`[data-review-group="${CSS.escape(groupId)}"][data-review-item="${CSS.escape(itemId)}"] button`).forEach(b=>b.classList.toggle('on',b.dataset.status===status));updateReviewSuggestion();scheduleDraftSave();}
function v10ReviewGroupHTML(a){const result=V10.reviewResults[a.id]||{};return `<div class="v10-review-group"><h4>${v10Esc(a.groupName)}</h4><div class="v10-review-note">قيّم كل سورة مستقلة: ✓ تم · ↺ يعاد · — لم يُسمع</div>${a.items.map(it=>{const st=result[it.id]?.status||'';return `<div class="v10-review-item" data-review-group="${v10Esc(a.id)}" data-review-item="${v10Esc(it.id)}"><div class="v10-review-name">${v10Esc(it.surahName)} <button class="v10-text-btn" onclick="openQuranRangeText({surah:'${v10Esc(it.surahName)}',from:1,to:${S[it.surahId-1]?.a||1}})">📖 النص</button></div><div class="v10-review-status"><button aria-label="تم" data-status="completed" class="${st==='completed'?'on':''}" onclick="setReviewItemStatus('${v10Esc(a.id)}','${v10Esc(it.id)}','completed')">✓</button><button aria-label="يعاد" data-status="repeat" class="${st==='repeat'?'on':''}" onclick="setReviewItemStatus('${v10Esc(a.id)}','${v10Esc(it.id)}','repeat')">↺</button><button aria-label="لم يسمع" data-status="not_heard" class="${st==='not_heard'?'on':''}" onclick="setReviewItemStatus('${v10Esc(a.id)}','${v10Esc(it.id)}','not_heard')">—</button></div></div>`}).join('')}</div>`;}
function loadPrevTask(excludeId=''){if(!curStId)return;const dateKey=document.getElementById('sesDate')?.value||localDateKey(),prev=getPreviousPresentSession(curStId,dateKey,excludeId),el=document.getElementById('prevContent');actualRecitation={new:null,rec:null,far:null};V10.reviewResults={};const current=editingSessionId?sessions.find(x=>x.id===editingSessionId):null;for(const a of current?.reviewResults||[]){V10.reviewResults[a.id]={};for(const it of a.items||[])V10.reviewResults[a.id][it.id]={status:it.status||'not_heard'};}if(!prev){el.innerHTML='<div class="txt-mut" style="padding:8px;text-align:center">لا توجد حصة سابقة</div>';updateReviewSuggestion();return;}const d=new Date(prev.date).toLocaleDateString('ar-EG',{weekday:'long',month:'long',day:'numeric'});let html=`<div class="txt-mut mb8">التكليف من حصة: ${d}</div>`;for(const [key,label] of [['new','الحفظ الجديد'],['rec','المراجعة القريبة'],['far','المراجعة البعيدة']]){const x=prev[key];if(!x)continue;actualRecitation[key]={surahId:x.surahId||S.findIndex(q=>q.n===x.surah)+1,surah:x.surah,from:Number(x.from)||1,to:Number(x.to)||Number(x.from)||1,full:!!x.full};const desc=x.full?`سورة ${v10Esc(x.surah)} كاملة`:`سورة ${v10Esc(x.surah)} من الآية ${v10Esc(x.from)} إلى الآية ${v10Esc(x.to)}`;html+=`<div class="prev-task-card" id="prev-task-${key}"><div class="v10-prev-head"><b>${label}</b><div class="v10-prev-tools"><button class="v10-text-btn" onclick="openPrevQuranText('${key}')">📖 النص</button></div></div><div class="assigned-range">المطلوب: ${desc}</div>${actualBlockHTML(key,x)}<div class="assessment-label">تقييم التسميع</div><div class="gbs" id="pgr-${key}">${['ممتاز','جيد جداً','جيد','ضعيف'].map(g=>`<div class="gb" data-g="${g}" onclick="setPrevGr('${key}','${g}')">${g==='ممتاز'?'⭐ ':''}${g}</div>`).join('')}</div><div id="v10-repeat-${key}"></div></div>`;}
 const ras=Array.isArray(prev.reviewAssignments)&&prev.reviewAssignments.length?prev.reviewAssignments:[...(prev.juz?.chips?.length?[v10Assignment('juz','مراجعة الأجزاء',prev.juz.chips)]:[]),...(prev.surahReview?.chips?.length?[v10Assignment('surah_group','مراجعة السور',prev.surahReview.chips)]:[])];if(ras.length)html+=ras.map(v10ReviewGroupHTML).join('');if(!prev.new&&!prev.rec&&!prev.far&&!ras.length)html+='<div class="txt-mut">لا يوجد تكليف للحصة السابقة</div>';el.innerHTML=html;['new','rec','far'].forEach(updateActualResult);paintPrevGrades();updateReviewSuggestion();}
function setPrevGr(key,g){g=v10NormalizeGrade(g);prevGrades[key]=g;document.querySelectorAll(`#pgr-${key} .gb`).forEach(b=>b.classList.toggle('sel',b.dataset.g===g));const spot=document.getElementById('v10-repeat-'+key);if(spot)spot.innerHTML=g==='ضعيف'?`<button type="button" class="v10-inline-action v10-repeat-same" onclick="repeatPrevAssignment('${key}')">↺ نفس التكليف للحصة القادمة</button>`:'';if(g!=='ضعيف')smartContinueFromAssessment(key,g);else{const hint=document.getElementById(key+'-auto-hint');if(hint)hint.textContent='التقييم ضعيف: لن يكرر النظام التكليف تلقائيًا.';}scheduleDraftSave();}
function updateReviewSuggestion(){const prev=v10Prev(),body=document.getElementById('v10SuggestionBody');if(!body)return;const ras=prev?.reviewAssignments||[];const remaining=[];for(const a of ras){for(const it of a.items||[]){const st=V10.reviewResults[a.id]?.[it.id]?.status;if(st==='repeat'||st==='not_heard')remaining.push(it);}}if(!remaining.length){body.innerHTML='<div class="v10-empty">لا توجد سور محددة للإعادة حتى الآن. اختر ↺ أو — بجوار السورة ليظهر الاقتراح.</div>';return;}body.innerHTML=`<div class="v10-review-summary"><b>المتبقي المقترح:</b> ${remaining.map(x=>v10Esc(x.surahName)).join('، ')}</div><div class="v10-review-actions"><button class="btn btn-g btn-sm" onclick="applyRemainingReviewSuggestion()">إضافة السور غير المُتقنة فقط</button><button class="btn btn-out btn-sm" onclick="toggleV10Accordion('v10SuggestionAccordion')">اتركه كاقتراح فقط</button></div>`;}
function applyRemainingReviewSuggestion(){const prev=v10Prev(),remaining=[];for(const a of prev?.reviewAssignments||[]){for(const it of a.items||[]){const st=V10.reviewResults[a.id]?.[it.id]?.status;if(st==='repeat'||st==='not_heard')remaining.push('سورة '+it.surahName);}}if(!remaining.length)return toast('لا توجد عناصر غير متقنة محددة','info');secOn.surahReview=true;surahReviewChips=[...new Set(remaining)];updateTogs();renderChips();renderSurahChecklist();scheduleDraftSave();toast('أضيفت السور غير المتقنة فقط — يمكنك الحذف أو الإضافة قبل الحفظ','success');}
function v10BuildReviewAssignments(){const out=[];if(secOn.juz&&juzChips.length)out.push(v10Assignment('juz','مراجعة الأجزاء',juzChips));if(secOn.surahReview&&surahReviewChips.length)out.push(v10Assignment('surah_group','مراجعة السور',surahReviewChips));return out;}
function buildSesData(){const d=globalThis.__IMAM_BASE__.buildSesData();d.reviewAssignments=v10BuildReviewAssignments();const results=[];const prev=v10Prev();for(const a of prev?.reviewAssignments||[]){const map=V10.reviewResults[a.id]||{};results.push({...a,items:(a.items||[]).map(it=>({...it,status:map[it.id]?.status||'not_heard'}))});}d.reviewResults=results;return d;}
function captureDraft(){const d=globalThis.__IMAM_BASE__.captureDraft();d.v10ReviewResults=JSON.parse(JSON.stringify(V10.reviewResults));d.v10Accordion={...V10.accordion};return d;}
function applyDraft(d){globalThis.__IMAM_BASE__.applyDraft(d);const restoredResults=d?.v10ReviewResults||{};V10.reviewResults=restoredResults;V10.accordion={errors:false,suggestion:false,...(d?.v10Accordion||{})};setTimeout(()=>{loadPrevTask(editingSessionId||'');V10.reviewResults=restoredResults;document.querySelectorAll('.v10-review-item').forEach(row=>{const g=row.dataset.reviewGroup,i=row.dataset.reviewItem,st=V10.reviewResults[g]?.[i]?.status;row.querySelectorAll('button[data-status]').forEach(b=>b.classList.toggle('on',b.dataset.status===st));});updateReviewSuggestion();for(const [id,k] of [['v10ErrorsAccordion','errors'],['v10SuggestionAccordion','suggestion']]){const e=document.getElementById(id);if(e){e.classList.toggle('open',!!V10.accordion[k]);e.querySelector(':scope > button')?.setAttribute('aria-expanded',String(!!V10.accordion[k]));}}},0);}
function injectFacebookSetting(){const pg=document.getElementById('pg-settings');if(!pg||document.getElementById('v10FacebookSetting'))return;const el=document.createElement('div');el.className='card';el.id='v10FacebookSetting';el.innerHTML=`<div class="ch">🔗 التواصل والهوية</div><div class="fld"><label>رابط صفحة Facebook</label><input id="v10FacebookUrl" type="url" dir="ltr" placeholder="https://www.facebook.com/..." value="${v10Esc(settings.facebookUrl||'')}" oninput="settings.facebookUrl=this.value.trim();save()"></div>`;pg.prepend(el);}
function renderV10ThemeSettings(){const host=document.getElementById('v10ThemeSettings');if(!host)return;host.innerHTML=`<div class="ch">🎨 نمط الألوان</div><div class="v10-theme-grid">${Object.entries(V10_THEMES).map(([k,t])=>`<button class="v10-theme-choice ${settings.themePalette===k?'on':''}" onclick="setV10Theme('${k}')"><div class="v10-theme-swatch" style="background:${t.p}"></div><b>${k} — ${t.name}</b></button>`).join('')}</div>`;}
function injectThemeSettings(){const pg=document.getElementById('pg-settings');if(!pg||document.getElementById('v10ThemeSettings'))return;const el=document.createElement('div');el.className='card';el.id='v10ThemeSettings';pg.insertBefore(el,pg.children[1]||null);renderV10ThemeSettings();}
function academyFooter(){let x=`${settings.circle||ACADEMY_NAME}\n${ACADEMY_TAGLINE}`;if(settings.facebookUrl)x+=`\n\nتابعونا على فيسبوك:\n${settings.facebookUrl}`;return x;}
const V10_BASE_WA=buildWAMsg;function buildWAMsg(st,ses){const date=new Date(ses?.date||Date.now()).toLocaleDateString('ar-EG',{weekday:'long',year:'numeric',month:'long',day:'numeric'});const pg=ses?.prevGrades||{};let msg=`السلام عليكم ورحمة الله وبركاته\n\nتقرير حصة الطالب: *${st.name}*\n📅 ${date}`;const assessed=[['new','الحفظ'],['rec','المراجعة القريبة'],['far','المراجعة البعيدة']].filter(([k])=>pg[k]);if(assessed.length){msg+='\n\n🎧 *نتيجة التسميع*';for(const [k,l] of assessed)msg+=`\n${l}: ${pg[k]}${ses.actualRecitation?.[k]?' — '+fmtSection(ses.actualRecitation[k]):''}`;}msg+='\n\n*التكليف القادم*';if(ses?.new)msg+=`\nالحفظ: ${fmtSection(ses.new)}`;if(ses?.rec)msg+=`\nالمراجعة القريبة: ${fmtSection(ses.rec)}`;if(ses?.far)msg+=`\nالمراجعة البعيدة: ${fmtSection(ses.far)}`;const rev=(ses?.reviewAssignments||[]).flatMap(a=>a.items||[]).map(i=>i.surahName);if(rev.length)msg+=`\nالمراجعة: ${[...new Set(rev)].join('، ')}`;if(!ses?.new&&!ses?.rec&&!ses?.far&&!rev.length)msg+='\nلا يوجد تكليف مسجل';if(ses?.notes)msg+=`\n\nملاحظة المحفظ:\n${ses.notes}`;msg+=`\n\n──────────\n\n${academyFooter()}`;return msg;}
function injectLibraries(){const more=document.getElementById('pg-more')||document.getElementById('pg-settings');if(!more||document.getElementById('v10Libraries'))return;const card=document.createElement('div');card.className='card';card.id='v10Libraries';card.innerHTML=`<div class="ch">📚 المحتوى التربوي</div><div class="settings-actions"><button class="btn btn-out btn-sm" onclick="openV10Library('hadith')">الحديث النبوي</button><button class="btn btn-out btn-sm" onclick="openV10Library('dua')">الأدعية والأذكار</button></div>`;more.prepend(card);if(!document.getElementById('v10LibraryModal'))document.body.insertAdjacentHTML('beforeend',`<div class="mo" id="v10LibraryModal"><div class="mo-box"><div class="mo-title"><span id="v10LibraryTitle">المكتبة</span><button class="mo-x" onclick="document.getElementById('v10LibraryModal').classList.remove('open')">✕</button></div><div class="v10-source-warning">المحتوى الظاهر هنا لا يُنشأ بالذكاء الاصطناعي. لا يُقبل أي عنصر دون مصدر ومرجع. النسخة الحالية تحتوي مجموعة بداية موثقة، وبنية المكتبة جاهزة لاستيراد المجموعة الكاملة بعد مراجعة المصدر.</div><div id="v10LibraryBody"></div></div></div>`);}
function openV10Library(type){V10.library.type=type;document.getElementById('v10LibraryTitle').textContent=type==='hadith'?'الحديث النبوي':'الأدعية والأذكار';renderV10Library();document.getElementById('v10LibraryModal').classList.add('open');}
function renderV10Library(){const type=V10.library.type||'hadith',data=type==='hadith'?V10_HADITH:V10_DUA,cats=['الكل',...new Set(data.map(x=>x.category))],f=type==='hadith'?V10.library.hadithFilter:V10.library.duaFilter,rows=data.filter(x=>f==='الكل'||x.category===f),body=document.getElementById('v10LibraryBody');body.innerHTML=`<div class="v10-library-tabs">${cats.map(c=>`<button class="${f===c?'on':''}" onclick="setV10LibraryFilter('${v10Esc(c)}')">${v10Esc(c)}</button>`).join('')}</div>${rows.map(x=>`<article class="v10-library-card"><div class="v10-arabic-text">«${v10Esc(x.text)}»</div><div class="v10-meta">${type==='hadith'?`الراوي: ${v10Esc(x.narrator)}<br>المصدر: ${v10Esc(x.source)}<br>رقم الحديث: ${v10Esc(x.hadithNumber)}<br>الدرجة: ${v10Esc(x.grade)}`:`المناسبة: ${v10Esc(x.occasion)}<br>المصدر: ${v10Esc(x.source)}<br>التكرار: ${x.repeatCount||1}` }<br>المرجع: ${v10Esc(x.reference)}</div><div class="v10-library-actions"><button class="btn btn-g btn-sm" onclick="assignV10Content('${type}','${v10Esc(x.id)}')">إضافة لطالب</button><button class="btn btn-out btn-sm" onclick="copyTextSafe('${v10Esc(x.text).replace(/'/g,"\\'")}').then(()=>toast('تم النسخ','success'))">نسخ</button></div></article>`).join('')||'<div class="v10-empty">لا توجد عناصر في هذا التصنيف.</div>'}`;}
function setV10LibraryFilter(c){if(V10.library.type==='hadith')V10.library.hadithFilter=c;else V10.library.duaFilter=c;renderV10Library();}
function assignV10Content(type,id){const data=type==='hadith'?V10_HADITH:V10_DUA,item=data.find(x=>x.id===id);if(!item)return;const names=students.filter(s=>!s.studentStatus||s.studentStatus==='active');const pick=prompt('اكتب رقم الطالب:\n'+names.map((s,i)=>`${i+1}) ${s.name}`).join('\n'));const st=names[Number(pick)-1];if(!st)return;settings.contentAssignments[st.id]=settings.contentAssignments[st.id]||{};settings.contentAssignments[st.id][type]={contentId:id,status:'learning',assignedAt:new Date().toISOString(),history:[]};save();toast(`تم تعيين ${type==='hadith'?'الحديث':'الدعاء'} للطالب ${st.name}`,'success');}
function injectProfileWeeklyContent(){if(!curStId)return;const host=document.getElementById('profHdr')?.parentElement;if(!host)return;document.getElementById('v10WeeklyContent')?.remove();const a=settings.contentAssignments?.[curStId];if(!a)return;const parts=[];for(const type of ['hadith','dua']){const as=a[type];if(!as)continue;const item=(type==='hadith'?V10_HADITH:V10_DUA).find(x=>x.id===as.contentId);if(item)parts.push(`<div><b>${type==='hadith'?'حديث الحفظ':'دعاء الأسبوع'}:</b> ${v10Esc(item.text)}<br><small>الحالة: ${as.status==='learning'?'قيد الحفظ':as.status}</small> <button class="v10-inline-action" onclick="gradeV10Content('${type}','completed')">✓ حفظه</button> <button class="v10-inline-action" onclick="gradeV10Content('${type}','repeat')">↺ يعاد</button></div>`);}if(parts.length)host.insertAdjacentHTML('afterbegin',`<div class="v10-weekly-card" id="v10WeeklyContent">${parts.join('<hr>')}</div>`);}
function gradeV10Content(type,status){const a=settings.contentAssignments?.[curStId]?.[type];if(!a)return;a.history=a.history||[];a.history.push({status,at:new Date().toISOString()});a.status=status==='completed'?'completed':'learning';save();injectProfileWeeklyContent();}
function injectMushafDirectDownload(){/* v9.2 already provides explicit external download + import fallback; preserve it and label the distinction clearly. */const el=document.getElementById('v9MushafApp');if(!el)return;setTimeout(()=>{const head=el.querySelector('.v92-mushaf-head');if(head&&!head.querySelector('.v10-source-warning'))head.insertAdjacentHTML('afterend','<div class="v10-source-warning"><b>نوع التنزيل:</b> الزر الحالي يفتح تنزيلًا خارجيًا ثم تستورد PDF داخل التطبيق. إذا منع المصدر CORS فلا يدّعي التطبيق وجود تنزيل مباشر داخلي أو Resume غير حقيقي.</div>');},0);}
function initV10(){v10Migrate();enhanceSessionAccordions();injectFacebookSetting();injectThemeSettings();injectLibraries();if(curPage==='mushaf')renderV9Mushaf();}
document.addEventListener('DOMContentLoaded',()=>setTimeout(initV10,50));
