const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.join(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
function assert(cond,msg){if(!cond)throw new Error(msg);}
const html=read('index.html');
const app=read('app.js');
const v8=read('v8.js');
const sw=read('sw.js');
const manifest=JSON.parse(read('manifest.json'));
const version=read('VERSION').trim();
new vm.Script(app,{filename:'app.js'});
new vm.Script(v8,{filename:'v8.js'});
new vm.Script(sw,{filename:'sw.js'});
assert(version==='8.0.0','VERSION must be 8.0.0');
assert(html.includes('content="8.0.0"'),'HTML application-version mismatch');
assert(app.includes("const APP_VERSION='8.0.0'"),'app.js APP_VERSION mismatch');
assert(sw.includes("const APP_VERSION = '8.0.0'"),'sw.js APP_VERSION mismatch');
assert(sw.includes("'./v8.js'"),'service worker must cache v8.js');
assert(manifest.display_override?.includes('window-controls-overlay'),'manifest missing desktop display override');
['pg-tasks','taskModal','quickSearchModal','platformStatus','homeAnalysis','weeklyGoalsCard','sessionJourneyCard','sessionErrorsCard','quranTextModal','appLockOverlay','profStop','profMap','profErrors'].forEach(id=>assert(html.includes(`id="${id}"`),`missing #${id}`));
['renderTasks','renderHomeAnalysis','openQuickSearch','setupKeyboardShortcuts','shareBackup','renderSurahReviewChips'].forEach(fn=>assert(new RegExp(`function\\s+${fn}\\s*\\(`).test(app),`missing ${fn}()`));
['initV8Layer','smartContinueFromAssessment','renderReviewSuggestions','addRecitationError','renderProgressMap','renderStudentTimeline','openQuranTextModal','playQuranRange','setupPinLock','createAutoBackup','pushCloudSync','pullCloudSync','printMonthlyStudentReport'].forEach(fn=>assert(new RegExp(`function\\s+${fn}\\s*\\(`).test(v8),`missing v8 ${fn}()`));
assert(html.includes('id="tog-juz"')&&html.includes('id="tog-surahReview"'),'parts and surah review must be independent');
assert(!html.includes('id="gr-new"')&&!html.includes('id="gr-rec"')&&!html.includes('id="gr-far"'),'assignment rating controls must not appear in current-task sections');
assert(html.includes('id="new-surah-dropdown"')&&html.includes('id="rec-surah-dropdown"')&&html.includes('id="far-surah-dropdown"'),'missing searchable surah dropdowns');
assert(html.includes('Husary_128kbps')&&html.includes('Alafasy_128kbps'),'required reciters missing');
assert(v8.includes('api.quran.com/api/v4/quran/verses/qpc_hafs'),'QPC Hafs endpoint missing');
assert(v8.includes('everyayah.com/data/'),'EveryAyah audio source missing');
assert(app.includes('جزء تبارك')&&app.includes('جزء عمّ'),'named juz labels missing');
assert(app.includes('const SCHEMA_VERSION=10'),'schema version must be 10');
['icon-96.png','icon-192.png','icon-512.png','icon-maskable.png','screenshots/mobile-home.png','screenshots/desktop-home.png','sql/supabase-sync.sql'].forEach(f=>assert(fs.existsSync(path.join(root,f)),`missing ${f}`));
console.log('Static checks passed for Imam Academy v8.0.0');
