const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.join(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
function assert(cond,msg){if(!cond)throw new Error(msg);}
const html=read('index.html');
const app=read('app.js');
const v8=read('v8.js');
const v9=read('v9.js');
const css9=read('v9.css');
const sw=read('sw.js');
const manifest=JSON.parse(read('manifest.json'));
const version=read('VERSION').trim();
new vm.Script(app,{filename:'app.js'});
new vm.Script(v8,{filename:'v8.js'});
new vm.Script(v9,{filename:'v9.js'});
new vm.Script(sw,{filename:'sw.js'});
assert(version==='9.0.0','VERSION must be 9.0.0');
assert(html.includes('content="9.0.0"'),'HTML application-version mismatch');
assert(app.includes("const APP_VERSION='9.0.0'"),'app.js APP_VERSION mismatch');
assert(app.includes('const SCHEMA_VERSION=11'),'schema version must be 11');
assert(sw.includes("const APP_VERSION = '9.0.0'"),'sw.js APP_VERSION mismatch');
assert(sw.includes("'./v9.js'")&&sw.includes("'./v9.css'"),'service worker must cache v9 assets');
assert(manifest.display_override?.includes('window-controls-overlay'),'manifest missing desktop display override');
['pg-mushaf','v9MushafApp','v9Nav','v9MoreSheet','v9Onboarding','quranTextModal','sessionJourneyCard'].forEach(id=>assert(html.includes(`id="${id}"`),`missing #${id}`));
['initV9Layer','renderV9Home','setSessionMode','setSessionStep','openOfficialMushafPortal','importMushafPDF','openMushafReader','toggleMushafBookmark','toggleMushafView','downloadQuranTextPack','markAllPresentV9','createDemoData','openGroupOverview'].forEach(fn=>assert(new RegExp(`function\\s+${fn}\\s*\\(`).test(v9),`missing v9 ${fn}()`));
assert(v8.includes('globalThis.__IMAM_V8_BASE__'),'v8-to-v9 compatibility bridge missing');
assert(v9.includes('globalThis.__IMAM_V8_BASE__'),'v9 must consume v8 compatibility bridge');
assert(v9.includes('dm.qurancomplex.gov.sa/hafsdownload/'),'official Mushaf portal missing');
assert(v9.includes('dm.qurancomplex.gov.sa/Download/1441-AI-hafs.zip'),'official AI package missing');
assert(v9.includes('Husary_128kbps')||v8.includes('Husary_128kbps'),'Husary reciter missing');
assert(v8.includes('Alafasy_128kbps'),'Alafasy reciter missing');
assert(css9.includes('.v9-nav')&&css9.includes('.v9-session-steps')&&css9.includes('.v9-mushaf-hero'),'v9 design system incomplete');
assert(html.includes('id="tog-juz"')&&html.includes('id="tog-surahReview"'),'parts and surah review must remain independent');
assert(!html.includes('id="gr-new"')&&!html.includes('id="gr-rec"')&&!html.includes('id="gr-far"'),'assignment rating controls must not return');
['icon-96.png','icon-192.png','icon-512.png','icon-maskable.png','styles.css','v9.css','app.js','v8.js','v9.js','MUSHAF-SOURCES.md','V9-IMPLEMENTATION.md'].forEach(f=>assert(fs.existsSync(path.join(root,f)),`missing ${f}`));
console.log('Static checks passed for Imam Academy v9.0.0');
